### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by rubenvde** [kopiro/node-spotify-webplayer-accesstoken#2]
I think Spotify added a reCAPTCHA button and now it isn't working anymore. I'm getting the statusMessage: 'Bad Request' error. I also tried @enriquegh his implementation in python but that didn't work either. The issue on his page you can find [here](https://github.com/enriquegh/spotify-webplayer-token/issues/1).

**Comment by kopiro** [comment]
Yeah, I know. I noticed that a week ago :(
I'm trying to find a workaround, but reCAPTCHA is very hard to bypass.
I'll let you know.

**Comment by remorses** [comment]
The only way is to use some service that resolves the captcha and then login

**Comment by kopiro** [comment]
@rubenvde and @remorses please refer to version 2.0.0 using cookies.
